### ISSUE TITLE
Something

### ISSUE THREAD

**Issue by rutra8002** [dharmikumbhani/quiz-facilitator#5]
Work with google forms, but dont work with microsoft forms, I get an error:
Error: Evaluation failed: ReferenceError: FB_PUBLIC_LOAD_DATA_ is not defined
    at __puppeteer_evaluation_script__:1:31
    at ExecutionContext._evaluateInternal (C:\Users\LEGION\Downloads\quiz-facilitator-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\LEGION\Downloads\fquiz-facilitator-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async getGFQ (C:\Users\LEGION\Downloads\forms\getGF.js:38:27)

**Comment by Arturo2008** [comment]
![image](https://user-images.githubusercontent.com/96191787/166687113-d40f40a9-9ba4-4471-9970-a18d89ab60dd.png)

**Comment by Bikaauss** [comment]
were you able to fix it?
